services:

  sonarqube:
    container_name: sonarqube
    image: sonarqube:community
    restart: always
    ports:
      - "9000:9000"
    environment:
      - SONAR_FORCEAUTHENTICATION=false
      - SONAR_SEARCH_JAVAADDITIONALOPTS=-Dcluster.routing.allocation.disk.threshold_enabled=false
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  sonarqube_data:
    driver: local
  sonarqube_logs:
    driver: local
