services:
  oracle:
    image: gvenzl/oracle-free
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: 031210
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./docker/oracle/reset_password.sh:/container-entrypoint-initdb.d/reset_password.sh
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "system/031210@//localhost:1521/FREEPDB1", "as", "sysdba", "<<<", "exit"]
      interval: 10s
      timeout: 5s
      retries: 30

  app:
    build: .
    ports:
      - "58080:58080"
    depends_on:
      - oracle
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@oracle:1521:FREEPDB1
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: 031210

  sonarqube:
    container_name: sonarqube
    image: sonarqube:community
    restart: always
    ports:
      - "9000:9000"
    environment:
      - SONAR_FORCEAUTHENTICATION=false
      - SONAR_SEARCH_JAVAADDITIONALOPTS=-Dcluster.routing.allocation.disk.threshold_enabled=false
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs

volumes:
  oracle_data:
  sonarqube_data:
    driver: local
  sonarqube_logs:
    driver: local
